name: GitHub Actions Input Test

on:
  workflow_dispatch:
    inputs:
        BASE_URL:
          description: 'base url'
          required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [[ "test" == "test" ]]; then ls -la; exit 0; fi; if [[ "test"=="test" ]]; then
            echo "abc"
          else
            echo "else:test"
          fi


  # if [[ "test" == "test" ]]; then set +e; ls -la; set -e; fi; if [[ "test"=="test" ]]; then
  #   echo "abc"
  # else
  #   echo "else:test" == "test" ]]; then set +e; ls -la; set -e; fi; if [[ "test"
  # fi
          
# if [[ "${{github.event.inputs.BASE_URL}}" == "test" ]]; then 
#   echo "abc"
# else
#   echo "else: ${{github.event.inputs.BASE_URL}}" 
# fi
# if [[ "${{BASE_URL}}" == "abc"]]; then 
#            echo "abc"; 
#          fi
#   if [[ "test" == "test" ]]; then ls -la; fi; if [[ "testa" == "test" ]]; then 