name: GitHub Actions Input Test

on:
  workflow_dispatch:
    inputs:
        BASE_URL:
          description: 'base url'
          required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        if [[1]]; then 
          echo "abc"; 
        fi
      