name: GitHub Actions Input Test

on:
  workflow_dispatch:
    inputs:
        BASE_URL:
          description: 'base url'
          required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [[ "test" == "test" ]]; then ls -la; if [[ "testa" == "test" ]]; then 
            echo "abc: ${{github.event.inputs.BASE_URL}}"
          else
            echo "else: ${{github.event.inputs.BASE_URL}}" 
          fi
# if [[ "${{BASE_URL}}" == "abc"]]; then 
#            echo "abc"; 
#          fi
      